name: Verificação de Plágio

on:
  push:
    branches:
      - '**'

jobs:
  detectar-plagio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Preparar arquivos de cada branch (checkout por pasta)
        run: |
          mkdir -p submissions

          for BRANCH in $(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||'); do
            echo "Clonando $BRANCH..."
            git clone --branch "$BRANCH" --depth 1 https://github.com/${{ github.repository }} "temp_$BRANCH" || continue

            if [ -f "temp_$BRANCH/jogo.por" ]; then
              mkdir -p "submissions/$BRANCH"
              cp "temp_$BRANCH/jogo.por" "submissions/$BRANCH/jogo.por"
            fi
          done
  
  
  

      - name: Comparar arquivos com Python
        run: |
          ls submissions
          python3 compare.py

      - name: Instalar matplotlib e pandas
        run: pip install matplotlib pandas seaborn

      - name: Gerar gráfico de similaridade
        run: python3 grafico.py

      - name: Upload do gráfico
        uses: actions/upload-artifact@v4
        with:
          name: grafico-similaridade
          path: similaridade.png