name: Verificação de Plágio

on:
  push:
    branches:
      - '**'

jobs:
  detectar-plagio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Preparar arquivos de cada branch com git worktree
        run: |
          mkdir -p submissions
          mkdir -p branches

          for BRANCH in $(git branch -r | grep -v HEAD); do
            NAME=$(echo "$BRANCH" | sed 's|origin/||')
            git worktree add "branches/$NAME" "$NAME"
            if [ -f "branches/$NAME/jogo.por" ]; then
              mkdir -p "submissions/$NAME"
              cp "branches/$NAME/jogo.por" "submissions/$NAME/jogo.por"
            fi
          done
  

      - name: Comparar arquivos com Python
        run: |
          python3 compare.py

      - name: Upload do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-plagio
          path: report/
