name: Verificação de Plágio

on:
  push:
    branches:
      - '**'

jobs:
  detectar-plagio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Preparar arquivos de cada branch
        run: |
          mkdir -p submissions

          for BRANCH in $(git branch -r | grep -v HEAD); do
            STUDENT=$(echo "$BRANCH" | sed 's/origin\///')
            git checkout "$BRANCH" || continue

            if [ -f "jogo.por" ]; then
              mkdir -p "submissions/$STUDENT"
              cp "jogo.por" "submissions/$STUDENT/jogo.por"
            fi
          done

      - name: Comparar arquivos com Python
        run: |
          ls
          python3 compare.py

      - name: Upload do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-plagio
          path: report/
